### PR TITLE
Support also class-transformer 0.5.x

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Review by RonHouben — APPROVED** [review]

**Comment by stlovas** [comment]
ping

**Comment by pmettraux** [comment]
No one is taking care of this lib? @RonHouben

**Comment by epiphone** [comment]
@pmettraux I'll try to get to this in the weekend!

**Comment by epiphone** [comment]
Published in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v3.1.1

**Pull request merged**
